export const site = {
  name: "Would You Rather",
  tagline: "The game of impossible choices",
  /** ~55 chars. Used as the default <title> (search + browser tab). */
  title: "Would You Rather — iOS Party Game of Impossible Choices",
  titleTemplate: "%s | Would You Rather",
  /**
   * ~154 chars, benefit-led. Used for meta description + Open Graph.
   * Do not claim global vote comparison, contrarian scores, or “who is weird”.
   */
  description:
    "Would You Rather is the iOS party game of impossible choices — 1,500+ questions across 11 categories. Shuffle, write your own, play offline. No account. Free.",
  privacyDescription:
    "Privacy policy for Would You Rather by Lulo. No account required; favorites and history stay on your device.",
  keywords: [
    "would you rather app",
    "would you rather game ios",
    "party game questions",
    "icebreaker questions app",
    "iOS party game",
    "would you rather",
  ],
  locale: "en_US",
  language: "en",
  category: "games",
  /**
   * Canonical origin. Override at build time with NEXT_PUBLIC_SITE_URL.
   * TODO: replace the fallback with the real production domain.
   */
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://wouldyourather.app",
  /** Static fallback artwork. PNG Open Graph image is generated by opengraph-image.tsx. */
  ogImage: "/og.svg",
  ogImageAlt: "Would You Rather — the iOS party game of impossible choices",
  /** TODO: replace with the real App Store listing once the app is published. */
  appStoreUrl: "#",
  /**
   * Numeric App Store ID (e.g. "1234567890").
   * Leave empty until the listing is live — do not invent an ID.
   * `apple-itunes-app` / itunes metadata is omitted until this is set.
   */
  appStoreId: "",
  supportEmail: "saradrada@luloai.com",
  company: "Lulo",
} as const;

export const navLinks = [
  { href: "#features", label: "Features" },
  { href: "#packs", label: "Categories" },
  { href: "#how-it-works", label: "How It Works" },
] as const;

export const stats = [
  { value: "1,500+", label: "Questions" },
  { value: "11", label: "Categories" },
  { value: "5.0", label: "Rating", hasStar: true },
] as const;

/** True feature list for structured data and agents. Omit unshipped social-comparison features. */
export const appFeatures = [
  "1,500+ hand-written would-you-rather questions",
  "11 categories (Classic, Funny, Hard Choices, Philosophical, Relationships, Money, and more)",
  "Write your own questions in My Cards",
  "Shuffle",
  "Works offline",
  "No account or sign-up",
] as const;

export function absoluteUrl(path = "/"): string {
  const base = site.url.replace(/\/$/, "");
  if (!path || path === "/") {
    return `${base}/`;
  }
  return `${base}${path.startsWith("/") ? path : `/${path}`}`;
}

export function hasAppStoreId(): boolean {
  return site.appStoreId.length > 0;
}

export function hasAppStoreUrl(): boolean {
  return site.appStoreUrl.startsWith("http");
}
